<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>

		<AssemblyTitle>ShiftStoneRandomizer</AssemblyTitle>
		<Product>ShiftStoneRandomizer</Product>
		<Copyright>Copyright ©  2025</Copyright>

		<RumblePath>G:\SteamLibrary\steamapps\common\RUMBLE</RumblePath>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="G:\SteamLibrary\steamapps\common\RUMBLE\MelonLoader\net6\**\*.dll" Private="false" />
		<Reference Include="G:\SteamLibrary\steamapps\common\RUMBLE\MelonLoader\net35\**\*.dll" Private="false" />
		<Reference Include="G:\SteamLibrary\steamapps\common\RUMBLE\MelonLoader\Il2CppAssemblies\**\*.dll" Private="false" />
		<Reference Include="OBS_Control_API">
			<HintPath>G:\SteamLibrary\steamapps\common\RUMBLE\Mods\OBS_Control_API.dll</HintPath>
		</Reference>
		<Reference Include="RumbleModdingAPI">
			<HintPath>G:\SteamLibrary\steamapps\common\RUMBLE\Mods\RumbleModdingAPI.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="assets\randomizer" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="src\" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!--Copy to mods folder-->
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(RumblePath)\Mods&quot;" />
		<!--Copy to thunderstore package-->
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(ProjectDir)_Misc\ModPackage\Mods&quot;" />
		<Exec Command="COPY &quot;$(ProjectDir)README.md&quot; &quot;$(ProjectDir)_Misc\ModPackage&quot;" />
	</Target>
</Project>